### ISSUE TITLE
Implement decorator of `@JSONable` for convenience

### ISSUE THREAD

**Issue by shundroid** [ensan-hcl/CustardKit#10]
Now, we have to define `json()` methods to each of the jsonable classes, so I would like to make `@JSONable` decorator and reduce the redundancy.

**Comment by shundroid** [comment]
@ensan-hcl Is it OK to define `to_json` function and use it recursively instead of using `json` method defined in each class?

**Comment by ensan-hcl** [comment]
It's of course okay. I don't understand how it would be formed because you cannot extend `str` or `int` to have `to_json`, but if it were possible, it would be the best way.
