### ISSUE TITLE
stop using `zoom` in markdown files

### ISSUE THREAD

**Issue by ensan-hcl** [ensan-hcl/CustardKit#4]
`zoom` プロパティは非標準なので， `width/height` で指定するのが良いです。
もしくは， `transform` プロパティを使う手もありますが，ちょっと大げさな気がします。

_Originally posted by @shundroid in https://github.com/ensan-hcl/CustardKit/pull/1#discussion_r599179996_

**Comment by ensan-hcl** [comment]
This is due to the default behavior of my markdown editor **typora**. I considered about this but there are no ways to avoid this as far as I know. What do you think @shundroid ?

**Comment by shundroid** [comment]
Ok. It cannot be helped.
